#!/usr/bin/env node

// Dependencies
var express= require('express');
var dhs= require('./');

var commander= require('commander');
var touch= require('touch');
var open= require('open');

var path= require('path');

// Commands
commander
  .version(require('./package').version)
  .usage('<rootDir>')
  .option('-p, --port <number>','listening port <number>',59798)
  .option('-o, --open [browser]','open the `http://localhost`')
;

commander
  .command('touch [index]')
  .description('`touch [index].coffee [index].jade [index].styl`')
  .action(function(name){
    if(name==null){
      name= 'index';
    }

    touch.sync(name+'.coffee');
    touch.sync(name+'.jade');
    touch.sync(name+'.styl');
    process.exit(0);
  })
  .parse(process.argv)
;

commander
  .command('*')
  .description('boot the difficult-http-server at *<rootDir>')
  .action(function(rootDir,options){
    var app= express();
    app.use(dhs({cwd:path.resolve(process.cwd(),rootDir)}));
    app.listen(commander.port,function(){
      var url= 'http://localhost:'+commander.port;
      console.log('DifficultHTTPServer at %s using %s',url,rootDir);

      if(commander.open){
        var browser= commander.open===true ? null: commander.open;
        open(url,browser);
      }
    });
  })
;

commander.parse(process.argv);
if(process.argv.slice(2).length===0){
  commander.outputHelp();
}
