#!/usr/bin/env node

// Dependencies
var express= require('express');
var dhs= require('./');

var commander= require('commander');
var touch= require('touch');
var path= require('path');

// Commands
commander
  .version(require('./package').version)
  .usage('<rootDir>')
  .option('-p --port <number>','listening port <number>',59798)
;

commander
  .command('touch [index]')
  .description('touch the [index](.coffee .jade .styl)')
  .action(function(name){
    if(name==null){
      name= 'index';
    }

    touch.sync(name+'.coffee');
    touch.sync(name+'.jade');
    touch.sync(name+'.styl');
    process.exit(0);
  })
  .parse(process.argv)
;

commander
  .command('*')
  .description('boot the difficult-http-server at <rootDir>')
  .action(function(rootDir){
    var options= {
      cwd:path.resolve(process.cwd(),rootDir),
    };

    var app= express();
    app.use(dhs(options));
    app.listen(commander.port,function(){
      console.log('http://localhost:%s <- %s',commander.port,rootDir);
    });
  })
;

commander.parse(process.argv);
if(process.argv.slice(2).length===0){
  commander.outputHelp();
}
